databases:
  - name: cottage
    databaseName: cottage
    user: cottage_user

services:
  - type: web
    name: cottage
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cottage
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false